oasislabs/oasis.js

packages/common/package.json
packages/test/package.json
packages/types/package.json

Lerna won't publish these packages to npm.

Make some packages private

---

packages/gateway/rollup/rollup.config.ts
packages/gateway/src/http.ts
packages/gateway/src/index.ts
packages/gateway/src/session.ts
packages/gateway/test/session.spec.ts

Addresses https://github.com/oasislabs/oasis.js/issues/117

allow user defined headers

---

packages/service/src/idl.ts

Change legacy `mantle-interface` reference.

Update idl error message

---

packages/gateway/src/index.ts
packages/service/src/oasis-gateway.ts
packages/service/test/utils.ts

Addresses https://github.com/oasislabs/oasis.js/issues/175 as requested.

Add disconnect to OasisGateway interface

---

packages/service/src/service.ts
packages/service/test/deploy.spec.ts
packages/service/test/service.spec.ts

Addresses https://github.com/oasislabs/oasis.js/issues/128

Hide service state behind _inner

---

packages/ethereum/src/gateway/index.ts
packages/ethereum/src/gateway/transaction.ts
packages/service/src/oasis-gateway.ts

Add value to web3 rpc options

---

packages/confidential/src/aead.ts
packages/confidential/src/error.ts
packages/confidential/src/index.ts
packages/service/src/rpc.ts

Addresses https://github.com/oasislabs/oasis.js/issues/120

Remove magic numbers 

---

packages/ethereum/src/gateway/websocket.ts

Without this change, errors aren't propagated to the caller.

Reject async errors in websocket

---

packages/common/src/cbor.ts

Gives a better error than "Remaining bytes"

service: Cbor decode error

---

packages/service/src/coder/confidential.ts

Related https://github.com/oasislabs/oasis-parity/pull/158.

service: Don't implicitly decrypt logs

---

packages/client/src/index.ts

Expose fromWasm utilities

---

packages/common/src/bytes.ts

Addresses https://github.com/oasislabs/oasis.js/issues/114

common: parseNumber throws with number < 0

---

packages/confidential/src/ecdh-tweak/browser.ts

Addresses https://github.com/oasislabs/oasis.js/issues/115

Comment and unset aesKey

---

packages/ethereum/src/gateway/index.ts
packages/gateway/src/api.ts
packages/gateway/src/index.ts

Addresses https://github.com/oasislabs/oasis.js/issues/106.

Status check when constructing gateway

---

packages/confidential/src/index.ts

Addresses https://github.com/oasislabs/oasis.js/issues/121.

confidential: Validate length of ciphertext

---

packages/client/src/workspace.ts

Addresses https://github.com/oasislabs/oasis.js/issues/213

client: Read private key from config

---

packages/client/package.json
packages/client/src/workspace.ts
yarn.lock

Use XDG_CONFIG_DIR on macOS

---

packages/client/src/workspace.ts

I didn't run `yarn build` before publishing rc.12; hence this PR.

Pointless change for republishing

---

packages/client/package.json
packages/client/src/index.ts
packages/ethereum/package.json
packages/ethereum/src/gateway/index.ts
packages/ethereum/src/gateway/websocket.ts
packages/gateway/package.json
packages/gateway/src/index.ts
packages/service/package.json
packages/service/src/oasis-gateway.ts
packages/service/test/utils.ts

We want this for showing connection problems in our dashboard.

gateway: expose internal connection status

---

packages/client/package.json
packages/ethereum/package.json
packages/gateway/package.json
packages/service/package.json

This reverts commit 813865a1152079d176c2d3dec3594d9b1907a1bc.
the publish process will do this supposedly

Revert "bump versions"

---

packages/ethereum/src/gateway/index.ts
packages/ethereum/src/gateway/websocket.ts
packages/gateway/src/api.ts
packages/gateway/src/index.ts
packages/gateway/test/gateway.spec.ts

Addresses https://github.com/oasislabs/oasis.js/issues/185

Call unsubscribe endpoint

---

packages/ethereum/src/gateway/index.ts

print the jsonified receipt instead of `[object Object]`

Print receipt on error

---

packages/ethereum/src/gateway/websocket.ts

Addresses https://github.com/oasislabs/oasis.js/issues/239

Close websocket connections properly

---

packages/client/src/workspace.ts
packages/gateway/src/index.ts
packages/gateway/test/gateway.spec.ts

required by https://github.com/oasislabs/oasis-cli/pull/105

Update workspace to use new config format

---

packages/client/package.json
packages/client/src/workspace.ts
packages/client/test/unit/workspace.spec.ts
packages/service/src/deploy/index.ts

Addresses https://github.com/oasislabs/oasis.js/issues/282.

client: Fix workspace deploys

---

packages/service/test/deploy-header.spec.ts
packages/service/test/service.spec.ts
packages/service/test/utils.ts

Regression test for https://github.com/oasislabs/oasis.js/issues/272.

service: Test Service.at for hex strings

---

README.md
docs/examples.rst
docs/gateways.rst
docs/service.rst
packages/client/README.md
packages/common/README.md
packages/confidential/README.md
packages/gateway/README.md
packages/service/README.md
packages/test/README.md
packages/web3/README.md

Addresses
- https://github.com/oasislabs/oasis.js/issues/275 
- https://github.com/oasislabs/oasis.js/issues/271
- https://github.com/oasislabs/oasis.js/issues/269
- https://github.com/oasislabs/oasis.js/issues/273

doc updates

---

packages/service/src/deploy/header.ts

Needed for @david-yan to run benchmarks on deploys.

Expose deployCode api

---

docs/service.rst
packages/client/test/e2e/app/service.spec.ts
packages/client/test/e2e/service/src/main.rs
packages/service/package.json
packages/service/src/coder/oasis.ts
yarn.lock

Addresses https://github.com/oasislabs/oasis.js/issues/293.

camelCase event keys

---

packages/client/test/e2e/app/service.spec.ts
packages/client/test/integration/service.spec.ts
packages/service/src/deploy/index.ts
packages/service/test/deploy.spec.ts

Related https://github.com/oasislabs/oasis-chain/issues/54

Error when gasLimit isn't provided to confidential deploys

---

packages/common/src/index.ts

NB: safari (mobile) will want to include a [BigInt polyfill](https://github.com/GoogleChromeLabs/jsbi).

Accept numbers in Balance ctor

---

packages/client/package.json
packages/gateway/package.json

- @oasislabs/client@1.0.0-rc.30
- @oasislabs/gateway@1.0.0-rc.26

Publish gateway polling fix
