packages/service/src/deploy/index.ts, packages/service/src/idl.ts, packages/service/src/service.ts, packages/service/test/idl.spec.ts
@sharmaster96 noticed browsers complain about using WebAssembly.Module to synchronously load a wasm module. This switches to async loading.
=> Async WASM module loading

packages/common/src/bytes.ts, packages/confidential/package.json, packages/confidential/src/ecdh-tweak/browser.ts, packages/confidential/src/index.ts, packages/confidential/src/key-store.ts, packages/confidential/test/crypto.spec.ts, packages/ethereum/src/coder.ts, packages/ethereum/src/gateway/index.ts, packages/gateway/src/index.ts, packages/service/src/coder/confidential.ts, packages/service/src/coder/index.ts, packages/service/src/coder/oasis.ts, packages/service/src/oasis-gateway.ts, packages/service/src/rpc.ts, packages/service/src/service.ts, yarn.lock
Changes needed for confidential services to work with the new runtime:
* update deoxysii version
* cipher_len + aad_len as little endian
* misc bugs (browser tweak string is wrong + parse bytes as uint8array for public keys)
* decrypt/decode subscription events
* decrypt output errors when confidential transactions revert
Se the runtime for corresponding ciphertext layout changes.
=> Confidential updates

packages/confidential/src/key-store.ts
Using `me` conflicts with web3.js. So anyone developing, say, at localhost, will fetch old web3c.js localStorage keys in their browsers.
=> Change local storage localKeys path

packages/common/src/bytes.ts
Addresses https://github.com/oasislabs/oasis.js/issues/113.
=> Prepend 0 when parsing odd length hex strings

packages/client/package-lock.json, packages/client/package.json, packages/client/src/index.ts, packages/client/src/workspace.ts, packages/service/src/deploy/index.ts, packages/service/src/idl.ts, packages/service/src/index.ts, tsconfig.json, yarn.lock
```js
import oasis from '@oasislabs/client';
jest.setTimeout(20000);
describe('Quickstart Test', () => {
it('should deploy non-confidentially', async () => {
const service = await oasis.service.Quickstart.deploy({
header: {confidential: false},
});
expect(service).toBeTruthy();
});
afterAll(() => {
oasis.disconnect();
});
});
```
the config is created by the oasis cli and looks like
```toml
[profiles.local]
endpoint = 'http://localhost:8546'
mnemonic = 'range drive remove bleak mule satisfy mandate east lion minimum unfold ready'
```
=> Strong defaults for testing client

packages/common/package.json, packages/types/package.json
This makes it so that someone building on master can use `lerna run build:node` or `build:browser` to quickly build for one of the two targets.
=> Add build:(node|browser) to common and types

packages/gateway/src/session.ts
when running tutorial/hello-world/app
FAIL  test/service.spec.ts (7.604s)
HelloWorld Test
✕ deployed (6ms)
✕ known greeting
✕ insert new greeting in Samoan (1ms)
● HelloWorld Test › deployed
TypeError: Cannot read property 'headers' of undefined
at HttpSession.<anonymous> (node_modules/@oasislabs/gateway/src/session.ts:55:18)
at step (node_modules/node_modules/tslib/tslib.es6.js:99:23)
at Object.next (node_modules/node_modules/tslib/tslib.es6.js:80:53)
at node_modules/node_modules/tslib/tslib.es6.js:73:71
at __awaiter (node_modules/node_modules/tslib/tslib.es6.js:69:12)
at HttpSession.Object.<anonymous>.HttpSession.request (node_modules/@oasislabs/client/dist/index.umd.js:16790:17)
at HttpGateway.<anonymous> (node_modules/@oasislabs/gateway/src/index.ts:215:41)
at step …
=> gateway session fix empty headers

packages/ethereum/src/gateway/index.ts, packages/gateway/src/index.ts
These sanity checks were put in to provide feedback if the gateway was misconfigured.
However, the downside is that, if the tutorial tests finish within 3 seconds, they will error and complain about an unresolved promise (this is because we await a timeout for 3 seconds in the sanity check, waiting for a gateway response).
Temporarily removing these sanity checks to resolve that. We should add them back in a better way in the future (for example, we can do them before the very first request is sent through the gateway).
=> Remove gateway sanity check request

packages/ethereum/src/gateway/websocket.ts
blocks https://github.com/oasislabs/private-dashboard/issues/1070, where we want to show users when there's connection trouble to the gateway
=> websocket: detect and expose repeated connection errors

docs/workspace.rst, packages/client/src/workspace.ts
Addresses https://github.com/oasislabs/oasis.js/issues/236.
Note that this will not set the "default" gateway, so that we can avoid the potentially unexpected side effect if the user just wants to read the gateway.
Expected usage:
```
const gateway = oasis.workspace.gateway();
oasis.setGateway(gateway);
```
WIth these apis, there is no need to specify wallets or gateway urls outside of the oasis-cli configuration.
=> Expose workspace.gateway api

packages/client/scripts/test-browser.sh, packages/client/test/browser/service/index.html
Build was passing even though the browser test was failing. This fixes that.
Failing build (as desired): https://circleci.com/gh/oasislabs/oasis.js/872?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
=> Ensure build fails on browser test failure

packages/gateway/src/api.ts
axios on the browser does not allow the client to send a payload with a GET request. So, the workaround for this is the send a POST request. Already made the change to developer-gateway to allow a POST request
=> allow post code for getcode

README.md
The giant logo prevents seeing useful information without scrolling the page.
=> Remove giant logo from README

packages/client/src/workspace.ts
It is very confusing when we call `oasis deploy` and nothing happens. In this situation, we should just raise an error so that the user knows they are not complying with the API
=> workspace deploy with error message on constructor arguments

packages/client/package.json
This should be the last of the changes necessary to export types
```diff
*~/P/p/oasis.js% diff <(find . -path "*dist/lib/src/index.d.ts" | cut -d'/' -f 3 | sort) <(ls packages | sort)
0a1
> client
4a6
> test
```
=> Correctly specify types path for client

packages/client/src/index.ts, packages/common/src/index.ts, packages/service/src/deploy/header.ts, packages/service/src/index.ts, packages/service/src/rpc.ts
This fixes
```
error TS2694: Namespace '".../node_modules/@oasislabs/service/dist/lib/src/deploy/header"' has no exported member 'DeployHeader'.
31             deployCode: typeof import("@oasislabs/service/dist/lib/src/deploy/header").DeployHeader.deployCode;
```
when importing `@oasislabs/client` into a (non-RN) typescript project
=> Remove circular export from DeployHeader

packages/client/package.json, packages/client/src/index.ts, packages/client/test/e2e/app/service.spec.ts
Connecting to a `Service` with `Service.at` takes `Address` as a parameter. Since this is likely going to be a very common use case, it is a good idea to expose `Address` directly in `@oasislabs/client` to avoid having to import both `@oasislabs/client` and `@oasislabs/service`
=> Expose Address in main client

.circleci/config.yml
Builds are public on NPM. There's nothing that uses the hosted artifacts.
=> Remove unused deploy steps from CI

package.json, yarn.lock
this PR addresses an [XSS vulnerability](https://github.com/yahoo/serialize-javascript/security/advisories/GHSA-h9rv-jmmf-4pgx) that exists in not-Node runtimes only because the latter safely handles regex strings. It's not an issue for this project because this dev dependency is used by a Node-based build tool.
=> Squelch security warning popup

packages/client/test/browser/e2e/index.html, packages/client/test/browser/service/index.html, packages/client/test/e2e/app/service.spec.ts, packages/confidential/src/index.ts, packages/service/package.json, packages/service/src/deploy/header.ts, packages/service/src/deploy/index.ts, packages/service/src/rpc.ts, packages/service/test/deploy-header.spec.ts, packages/service/test/deploy.spec.ts, packages/service/test/service.spec.ts, yarn.lock
re: https://github.com/oasislabs/oasis-parity/pull/181
resolves #339
=> Provide salt to c10l deploys

packages/confidential/src/ecdh-tweak.ts, packages/confidential/src/index.ts, packages/gateway/src/index.ts, packages/gateway/src/session.ts
The "ciphertext too short" comes up all the time. The other used to come up for me and I have had that change stored locally for a long time. Cannot hurt to add it.
=> Increase verbosity of some errors

packages/client/package.json, packages/confidential/package.json, packages/gateway/package.json, packages/gateway/src/http.ts, packages/service/package.json, packages/test/package.json, packages/web3/package.json, yarn.lock
HTTP is the lowest-level layer through which Parcel SDK communicates with the other components (=gateway, mostly).
I've found this useful in my debugging.
This PR doesn't use the tiny TS logging class from oasis-std, because that would cause a cyclic depndency between the two packages.
=> Add low-level HTTP request logging

packages/client/package.json, packages/common/package.json, packages/common/src/db.ts, packages/confidential/package.json, packages/gateway/package.json, packages/service/package.json, packages/test/package.json, packages/web3/package.json
Resolves https://github.com/oasislabs/private-parcel/issues/786.
It should not be problematic to create LocalStorage in this new, less durable location, for two reasons: 1) Browser LocalStorage is also not guaranteed to be long-lasting, 2) The only uses that I can see are from gateway client and service.ts (which represents a WASM service), and neither of them need to retain state across machine reboots.
Testing:
```
nodejs
s = require('@oasislabs/common').LocalStorage
new s()
```
-- verified that it runs and that the location is in `/tmp`.
=> Create LocalStorage equivalent in /tmp

packages/client/package.json, packages/gateway/package.json, packages/gateway/src/http.ts, packages/gateway/src/polling.ts
PR #342 had an unexpected side effect where `IDLE_TIMELAPSE` started being heeded correctly. So all event polling ran for at most 60s. This is way too little for the offchain worker (that needs to wait possibly for days between jobs), and even for the offchain compute client (that needs to wait for the job to complete).
This PR extends the timeout to the point where it is practically disabled, but given that that is how we operated this whole time, the change should be non-controversial.
Should we do the same in Go?
More context: https://github.com/oasislabs/private-parcel/issues/842
=> Extend polling timeout
